kwwhat:
  target: duckdb
  outputs:
    duckdb:
      type: duckdb
      path: /data/analytics.duckdb
      attach:
        - path: /data/raw.duckdb
          alias: RAW
          read_only: true
      schema: ANALYTICS
      threads: 4
